# Site settings
lang: "en"
title: vd Brink Home Automations
description: "Home automations with Home Assistant, ESPHome, Node-RED and more tech"
url: "https://vdbrink.github.io"

defaults:
  - scope:
      path: "" # Alle bestanden in de root en submappen
    values:
      layout: "default"


# Layout settings (geen extra spaties vooraan!)
layouts_dir: _layouts

# Markdown & Syntax
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Plugins (Let op de exacte naam van de tagging plugin)
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll/tagging
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - webrick
  - jekyll-github-metadata

tagging:
  layout: default
  dir: tags
  permalink: /tag/:name/

# Zorg dat dit blok helemaal aan het begin van een regel staat (0 spaties)
sass:
  quiet_deps: true
  style: compressed

last-modified-at:
  date-format: 'last modified: %d/%b/%y'

google_analytics: G-WTTK5G664M

# Exclusies
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - TODO.md
  - preview.*
  - .jekyll-cache
  - _site
